version: "3"
services:
        server:
                build: ./server
                image: heaty566/my-chess-server:latest
                expose:
                        - 4000
        client:
                build: ./client
                image: heaty566/my-chess-client:latest
                expose:
                        - 3000
