name: auto-build-deploy

on:
        push:
                branches:
                        - "dev"
jobs:
        build-check:
                runs-on: ubuntu-latest
                steps:
                        - name: checking allow to build
                          run: |
                                  if [ ${{secrets.BUILD}} == ACTIVE ] 
                                  then
                                    echo '------------------- ready to deploy --------------------'
                                  else 
                                    echo 'not ready'
                                    exit 1
                                  fi

        deploy:
                runs-on: ubuntu-latest
                steps:
                        - name: executing remote ssh commands using ssh key
                          uses: appleboy/ssh-action@master
                          with:
                                  host: ${{ secrets.HOST }}
                                  username: ${{ secrets.USERNAME }}
                                  password: ${{ secrets.PASSWORD }}
                                  port: ${{ secrets.PORT }}
                                  script: |
                                          cd app
                                          docker-compose pull 
                                          docker-compose up -d
